modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
showAsResourcePack=false
issueTrackerURL="https://github.com/Huziyang520/Only-TP-Violent-Build/issues"
displayURL="https://github.com/Huziyang520/Only-TP-Violent-Build"
logoFile="assets/onlytpviolentbuild/icon.png"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description="${description}"
logoFile=""
[[mixins]]
config="${mod_id}.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
